Merged revision(s) 81426-81457 from FreshDirect/releases/branches/2018_Aug_R1: Merged revision(s) 81395, 81418 from FreshDirect/trunk: AppDev-7914 : Earliest availability message change for FDC ........ [SF17-108]: FDStandingOrdersManager/FDStandingOrdersSB ........
........
Merged revision(s) 81398, 81428 from FreshDirect/trunk:
Assistive options (IE bug fix ) and css fixes for Radio Button(Daniel approved)
........
Bug fix for IE assistive options (Daniel need some styling changes for radio button) and Timeslots screen reader bug fix for done and cancel buttons
........

........
Merged revision(s) 81456 from FreshDirect/trunk:
Fix for the following production error.

com.freshdirect.fdstore.FDResourceException
java.sql.SQLException: Invalid column name
	at weblogic.rjvm.ResponseImpl.unmarshalReturn(ResponseImpl.java:237)
	at weblogic.rmi.cluster.ClusterableRemoteRef.invoke(ClusterableRemoteRef.java:348)
	at weblogic.rmi.cluster.ClusterableRemoteRef.invoke(ClusterableRemoteRef.java:259)
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNew_61rww6_EOImpl_1036_WLStub.getPromotion(Unknown Source)
	at com.freshdirect.fdstore.promotion.management.FDPromotionNewManager.loadPromotion(FDPromotionNewManager.java:127)
	at com.freshdirect.webapp.taglib.promotion.GetPromotionNewTag.getResult(GetPromotionNewTag.java:23)
	at com.freshdirect.webapp.taglib.AbstractGetterTag.doStartTag(AbstractGetterTag.java:46)
	at jsp_servlet._shared.__promotion_popup._jspService(__promotion_popup.java:170)
	at weblogic.servlet.jsp.JspBase.service(JspBase.java:34)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:26)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.freshdirect.webapp.filters.OncePerRequestDateFilter.doFilter(OncePerRequestDateFilter.java:31)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.freshdirect.webapp.filters.WebTrackingCodeFilter.doFilter(WebTrackingCodeFilter.java:52)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.freshdirect.webapp.filters.URLRewriteFilter.doFilter(URLRewriteFilter.java:39)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.freshdirect.webapp.filters.WarmupMonitorFilter.doFilter(WarmupMonitorFilter.java:53)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at com.freshdirect.framework.monitor.WebRequestMonitor.doFilter(WebRequestMonitor.java:23)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3730)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3696)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2273)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1490)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
Caused by: com.freshdirect.fdstore.FDResourceException
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNewSessionBean.getPromotion(FDPromotionManagerNewSessionBean.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.bea.core.repackaged.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:310)
	at com.bea.core.repackaged.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)
	at com.bea.core.repackaged.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)
	at com.bea.core.repackaged.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
	at com.bea.core.repackaged.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
	at com.bea.core.repackaged.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at com.oracle.pitchfork.spi.MethodInvocationVisitorImpl.visit(MethodInvocationVisitorImpl.java:34)
	at weblogic.ejb.container.injection.EnvironmentInterceptorCallbackImpl.callback(EnvironmentInterceptorCallbackImpl.java:54)
	at com.oracle.pitchfork.spi.EnvironmentInterceptor.invoke(EnvironmentInterceptor.java:42)
	at com.bea.core.repackaged.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at com.bea.core.repackaged.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:89)
	at com.bea.core.repackaged.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at com.bea.core.repackaged.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
	at com.bea.core.repackaged.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
	at com.bea.core.repackaged.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
	at com.bea.core.repackaged.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at $Proxy127.getPromotion(Unknown Source)
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNew_61rww6_EOImpl.__WL_invoke(Unknown Source)
	at weblogic.ejb.container.internal.SessionRemoteMethodInvoker.invoke(SessionRemoteMethodInvoker.java:40)
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNew_61rww6_EOImpl.getPromotion(Unknown Source)
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNew_61rww6_EOImpl_WLSkel.invoke(Unknown Source)
	at weblogic.rmi.internal.BasicServerRef.invoke(BasicServerRef.java:667)
	at weblogic.rmi.cluster.ClusterableServerRef.invoke(ClusterableServerRef.java:230)
	at weblogic.rmi.internal.BasicServerRef$1.run(BasicServerRef.java:522)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:363)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:146)
	at weblogic.rmi.internal.BasicServerRef.handleRequest(BasicServerRef.java:518)
	at weblogic.rmi.internal.wls.WLSExecuteRequest.run(WLSExecuteRequest.java:118)
	... 2 more
java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3711)
	at oracle.jdbc.driver.OracleResultSetImpl.findColumn(OracleResultSetImpl.java:2806)
	at oracle.jdbc.driver.OracleResultSet.getInt(OracleResultSet.java:438)
	at weblogic.jdbc.wrapper.ResultSet_oracle_jdbc_driver_OracleResultSetImpl.getInt(Unknown Source)
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNewDAO.loadPromoDlvZoneStrategies(FDPromotionManagerNewDAO.java:1968)
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNewDAO.getPromotion(FDPromotionManagerNewDAO.java:110)
	at com.freshdirect.fdstore.promotion.management.ejb.FDPromotionManagerNewSessionBean.getPromotion(FDPromotionManagerNewSessionBean.java:81)
........

........


git-svn-id: https://appdevsvn.nj01/appdev/FreshDirect/features/branches/sf2_0_fe@81461 842219ff-9341-0410-a943-573460bdd4de