Adding 'aopalliance-1.0.jar' to the build, which is missing and required for running cron jobs in console.
Error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/aopalliance/aop/Advice
       at java.lang.Class.getDeclaredMethods0(Native Method)
       at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
       at java.lang.Class.getDeclaredMethods(Class.java:1791)
       at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:467)
       at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:451)
       at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:512)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:663)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:593)
       at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1396)
       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:382)
       at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:353)
       at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:97)
       at org.springframework

git-svn-id: https://appdevsvn.nj01/appdev/FreshDirect/trunk@76741 842219ff-9341-0410-a943-573460bdd4de