Merged revision(s) 86070-86082 from FreshDirect/releases/branches/2019_Feb_R2: Merged revision(s) 86056-86069 from FreshDirect/trunk: APPDEV-7672 Optimize Login/Masquerade performance for COS users.
........
[APPDEV-7660]-Fix for the following error while populating recommended products after ATP. These errors should be ignored in this case.


com.freshdirect.fdstore.FDRuntimeException: PricingException occured on DAI4201470 - FDConfiguration[1.0, unknown salesunit, {}]
com.freshdirect.common.pricing.PricingException: No salesUnitRatio found for unknown salesunit in Pricing[
        ZoneInfo:ZoneInfo [zoneId=0000100000, salesOrg=0001, distributionChanel=01, pricingIndicator=SALE, parent=null]
        MaterialPrice[$55.89 per CS scale: 0.0 - Infinity CSpromo 49.99]
        ZoneInfo:ZoneInfo [zoneId=0000201201, salesOrg=0001, distributionChanel=01, pricingIndicator=SALE, parent=null]
        MaterialPrice[$47.92 per CS scale: 0.0 - Infinity CSpromo 43.09]
        ZoneInfo:ZoneInfo [zoneId=0000201201, salesOrg=1400, distributionChanel=01, pricingIndicator=SALE, parent=null]
        MaterialPrice[$47.92 per CS scale: 0.0 - Infinity CSpromo 43.09]
        ZoneInfo:ZoneInfo [zoneId=0000100000, salesOrg=1400, distributionChanel=01, pricingIndicator=SALE, parent=null]
        MaterialPrice[$55.89 per CS scale: 0.0 - Infinity CSpromo 49.99]
]
        at com.freshdirect.fdstore.customer.FDProductSelection.performPricing(FDProductSelection.java:638)
        at com.freshdirect.fdstore.customer.FDProductSelection.refreshConfiguration(FDProductSelection.java:272)
        at com.freshdirect.webapp.ajax.product.ProductDetailPopulator.populateDetailProductData(ProductDetailPopulator.java:258)
        at com.freshdirect.webapp.ajax.product.ProductDetailPopulator.createProductData(ProductDetailPopulator.java:233)
        at com.freshdirect.webapp.ajax.product.ProductDetailPopulator.createProductData(ProductDetailPopulator.java:392)
        at com.freshdirect.webapp.ajax.product.ProductDetailPopulator.createProductData(ProductDetailPopulator.java:368)
--        at com.freshdirect.webapp.ajax.checkout.UnavailabilityPopulator.collectRecommendedProducts(UnavailabilityPopulator.java:252)--
        at com.freshdirect.webapp.ajax.checkout.UnavailabilityPopulator.processCartLine(UnavailabilityPopulator.java:202)
        at com.freshdirect.webapp.ajax.checkout.UnavailabilityPopulator.createUnavailabilityData(UnavailabilityPopulator.java:63)
        at com.freshdirect.webapp.ajax.expresscheckout.checkout.service.CheckoutService.applyAtpCheck(CheckoutService.java:113)
        at com.freshdirect.webapp.ajax.expresscheckout.service.SinglePageCheckoutFacade.loadByPageAction(SinglePageCheckoutFacade.java:274)
        at com.freshdirect.webapp.ajax.expresscheckout.restriction.servlet.RestrictionServlet.doPost(RestrictionServlet.java:80)
........

........
Merged revision(s) 86007, 86042, 86044 from FreshDirect/trunk:
[APPDEV-7868] Added datasource qualifiers to cms
........
resolving jdbc conflicts.
........
resolving  conflicts.
........

........


git-svn-id: https://appdevsvn.nj01/appdev/FreshDirect/features/branches/sf2_0_fe@86090 842219ff-9341-0410-a943-573460bdd4de