Adding 'httpclient-4.5.jar' to the build, which is missing and required for running the cron job:CaseCreationByReceivedSMSCron, in console.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager
        at com.freshdirect.dataloader.smsalerts.CaseCreationByReceivedSMSCron.main(CaseCreationByReceivedSMSCron.java:54)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.HttpClientConnectionManager
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)


git-svn-id: https://appdevsvn.nj01/appdev/FreshDirect/trunk@81740 842219ff-9341-0410-a943-573460bdd4de